Add Blog: Creating a Backstage Backend Plugin
janus-idp/janus-idp.github.io pull request #208
Opened 2023-08-23 10:22 UTC by relessawy

## What does this PR do / why we need it

New blog content: Creating your first Backstage Backend plugin

2023-08-23 12:11 UTC, schwesig requested changes
the following comments are not blocking this PR,
just comparing the source google sheet in the last version I know of.

If the changes were made on purpose, then an /LGTM /APPROVE from my side.

2023-08-23 12:11 UTC, schwesig commented on apps/website/blog/2023-08-23-creating-your-first-backstage-backend-plugin/index.mdx
> +## Structure of the Newly Created Plugin
```suggestion
### Structure of the Newly Created Plugin
```

2023-08-23 12:11 UTC, schwesig commented on apps/website/blog/2023-08-23-creating-your-first-backstage-backend-plugin/index.mdx
> +### Testing Your Backend Plugin
```suggestion
## Testing Your Backend Plugin
```

2023-08-23 12:11 UTC, schwesig commented on apps/website/blog/2023-08-23-creating-your-first-backstage-backend-plugin/index.mdx
> +## Standalone mode - Light Testing
```suggestion
### Standalone mode - Light Testing
```

2023-08-23 12:11 UTC, schwesig commented on apps/website/blog/2023-08-23-creating-your-first-backstage-backend-plugin/index.mdx
> +## Testing using Jest functions
```suggestion
### Testing using Jest functions
```

2023-08-23 12:11 UTC, schwesig commented on apps/website/blog/2023-08-23-creating-your-first-backstage-backend-plugin/index.mdx
> +### Conclusion
```suggestion
## Conclusion
```

2023-08-24 07:23 UTC, schwesig approved these changes
/lgtm
/approve

2023-08-24 13:45 UTC, tumido reviewed
Few suggestions above. Please run `pnpm prettier:fix` in the repo to make CI happy about the formatting.

2023-08-24 13:45 UTC, tumido commented on apps/website/blog/2023-08-23-creating-your-first-backstage-backend-plugin/index.mdx
> +```
```suggestion
```ts title="router.test.ts"
```

2023-08-24 13:45 UTC, tumido commented on apps/website/blog/2023-08-23-creating-your-first-backstage-backend-plugin/index.mdx
> +```
```suggestion
```ts title="router.ts"
```

2023-08-24 17:53 UTC, Zaperex commented on apps/website/blog/2023-08-23-creating-your-first-backstage-backend-plugin/index.mdx
> +Finally, you can start the Janus-Showcase application. To do this, navigate into the folder you cloned (backstage-showcase), then run the start command in iyour terminal.
```suggestion
Finally, you can start the Janus-Showcase application. To do this, navigate into the folder you cloned (backstage-showcase), then run the start command in your terminal.
```

2023-08-25 13:45 UTC, Zaperex approved these changes
LGTM

2023-08-25 15:27 UTC, merged